### ISSUE TITLE
Question regarding error handling

### ISSUE THREAD

**Issue by elifoster** [d-unseductable/ruru#20]
How are we supposed to handle returning errors? Since we can't throw exceptions from Rust, like we do with Ruby, and `unwrap`ing in library code is generally bad, I'm not really sure what we're supposed to do in this situation.

**Comment by jwilm** [comment]
AFAICT, you can't right now. To work around this, I've been wrapping Rust APIs in Ruby code. Definitely not ideal.

As for an actual solution, I've been thinking about updating the macros to expect a Result type back from methods. It might be possible to use `rb_error` at the FFI boundary then. This would give you Ruby exceptions from Rust. There may be a problem, though, since `rb_error` uses SJLJ error handling which unwinds the stack. Haven't had the time or urgency to try that out yet.

**Comment by d-unseductable** [comment]
Please take a look at #49 for handling exceptions and [`VM::raise()`](http://d-unseductable.github.io/ruru/ruru/struct.VM.html#method.raise) for raising them.
